Try fix

diff --git a/local/bin/brew b/local/bin/brew
--- a/local/bin/brew
+++ b/local/bin/brew
@@ -1,3 +1,7 @@
 #!/bin/sh
-eval `$HOME/.linuxbrew/bin/brew shellenv`
-exec $HOME/.linuxbrew/bin/brew "$@"
+if [ ! -x /home/linuxbrew/.linuxbrew/bin/brew ]; then
+    echo "$0: error: /home/linuxbrew/.linuxbrew/bin/brew does not exist or is not executable."
+    exit 1
+fi
+eval /home/linuxbrew/.linuxbrew/bin/brew shellenv
+exec /home/linuxbrew/.linuxbrew/bin/brew "$@"
